[project]
name = "hr-load-prediction"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[dependency-groups]
eda = [
    "ipykernel>=7.4.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "phik>=0.12.5",
    "seaborn>=0.13.2",
]
